# Pulsar Core latest (may be updated to latest version at any time)
launcher=core/4.17.0/pulsar.launcher-4.3.0.jar
modules=core/4.17.1/pulsar-modules-4.17.1.pulsar
apps=core/4.17.1/pulsar-apps-4.17.1.pulsar
endorsed=core/4.17.0/pulsar-endorsed-4.17.0.pulsar
docs=core/4.14.0/Pulsar 4.14.0 Documentation.pdf

# Pulsar SPA-UI latest (may be updated to latest version at any time)
spaui=spa-ui/hailmary/spa-ui-3.0.0.334-RC.pulsar
spaui-endorsed=spa-ui/hailmary/spa-ui-endorsed-3.0.0.334-RC.pulsar